language: php
os:
  - linux
dist: xenial

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer
    - var/cache

jobs:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phplint
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/phpstan
